# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a56f203fdf3f20fd258637a75c7bfe5d65da148b90ee2173d0857d38bd90663f9de4a6a81874e0eca87b04513c1ab16e7a8bfe1a79c34ba95a281f84dfe8fd5c

test:
  secret_key_base: 1a7db6d6c9a4b67267a9e8c961dc3f2a5a66cbe78d0f2a35bba6382fb27955825e5834831ee088fa2166e1ed1518d33718c954576f4bd8a9a501f00a7ce3af6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
